Update path folder for example file
r-hyperspec/hySpc.read.Witec pull request #44
Opened 2021-08-01 04:54 UTC by sangttruong

2021-08-01 14:45 UTC, bryanhanson reviewed
Checks failed due to file names exceeding CRAN limit... I think @cbeleites will have to decide how to handle this one.  Note that in `inst/extdata/fileio/...` I think you can remove the `fileio` subdirectory and move everything up (this is probably a legacy of having everything in the old `hyperSpec`).  This will save a few characters.

There are also issues with the unit tests which are "file not found" in nature so perhaps the UTs did not get the new paths?

2021-08-01 22:01 UTC, GegznaV requested changes
Please answer to the questions in my comments

2021-08-01 22:01 UTC, GegznaV commented on R/read_asc_Andor.R
> +#   on.exit(unlink(tmpdir))
This line should go after line 53. In case `untar()` fails, the `tmpdir` should get deleted anyway.

2021-08-01 22:01 UTC, GegznaV commented on R/read_dat_Witec.R
> +    capture_output(paste0(tmpdir, "/Witec-timeseries-x.dat"))
Why do we need to capture the output of `paste0()` function and do nothing with it?

2021-08-01 22:01 UTC, GegznaV commented on R/read_asc_Andor.R
> +#   test_that("Andor Solis .asc text files", {
Change into "Andor Solis .asc files are read correctly"

(So that it was a logical sentence to read "**Test that** Andor Solis .asc files are read correctly")

2021-08-02 09:49 UTC, GegznaV commented
@bryanhanson wrote:

>Note that in `inst/extdata/fileio/...` I think you can remove the `fileio` subdirectory and move everything up

I totally agree with this: `fileio` subdir is not needed anymore if files are moved to `inst/extdata`.

2021-08-02 09:51 UTC, GegznaV requested changes

2021-08-02 09:51 UTC, GegznaV commented on R/read_dat_Witec.R
> +    capture_output(paste0(tmpdir, "/Witec-timeseries-x.dat"))
If this line has no purpose, please, remove it.

2021-08-02 09:54 UTC, GegznaV commented
The new unit tests in this PR are commented and there are other new unit tests in #45. This will lead to Git conflict as the same file was changed in parallel branches.

2021-08-02 19:34 UTC, GegznaV approved these changes
Looks OK

2021-08-02 19:34 UTC, GegznaV commented on R/read_asc_Andor.R
> +#   test_that("Andor Solis .asc files are read correctly", {
OK

2021-08-02 19:34 UTC, merged